// Code generated by gocons; DO NOT EDIT.

package example

import (
	"database/sql"

	"github.com/shopspring/decimal"
)

func NewPerson(
	id string,
	name string,
	tags []string,
	desc sql.NullString,
	deposit *deposit,
) *Person {
	return &Person{
		id:      id,
		name:    name,
		tags:    tags,
		desc:    desc,
		deposit: deposit,
	}
}

func (x *Person) Id() string {
	return x.id
}

func (x *Person) Name() string {
	return x.name
}

func (x *Person) Tags() []string {
	return x.tags
}

func (x *Person) Desc() sql.NullString {
	return x.desc
}

func (x *Person) Deposit() *deposit {
	return x.deposit
}

func NewDeposit(
	charge decimal.Decimal,
) *deposit {
	return &deposit{
		charge: charge,
	}
}

func (x *deposit) Charge() decimal.Decimal {
	return x.charge
}
