// Code generated by gocons; DO NOT EDIT.

package example

func NewPerson(
	id string,
	name string,
) Person {
	return Person{
		id:   id,
		name: name,
	}
}

func (x Person) Id() string {
	return x.id
}

func (x Person) Name() string {
	return x.name
}
