// Code generated by gocons; DO NOT EDIT.

package example

import "database/sql"

func NewPerson(
	id string,
	name string,
	tags []string,
	desc sql.NullString,
) *Person {
	return &Person{
		id:   id,
		name: name,
		tags: tags,
		desc: desc,
	}
}

func (x *Person) Id() string {
	return x.id
}

func (x *Person) Name() string {
	return x.name
}

func (x *Person) Tags() []string {
	return x.tags
}

func (x *Person) Desc() sql.NullString {
	return x.desc
}
