package service

import (
	"fmt"

	"github.com/dave/jennifer/jen"
	"github.com/jinford/gocons/internal/domain/entity"
	"golang.org/x/tools/imports"
)

type CodeGenerater interface {
	GenerateCode(pkgName string, structs []*entity.Struct) ([]byte, error)
}

type codeGenerater struct {
	appName string
}

func NewCodeGenerator(appName string) CodeGenerater {
	return &codeGenerater{
		appName: appName,
	}
}

func (g *codeGenerater) GenerateCode(pkgName string, structs []*entity.Struct) ([]byte, error) {
	f := jen.NewFile(pkgName)
	f.HeaderComment(fmt.Sprintf("Code generated by %s; DO NOT EDIT.", g.appName))

	for _, s := range structs {
		f.Add(jen.Id(s.GenerateConstructorStatement()).Line())
		for _, getter := range s.GenerateGettersStatement() {
			f.Add(jen.Id(getter).Line())
		}

	}

	code := f.GoString()

	fmted, err := imports.Process("", []byte(code), nil)
	if err != nil {
		return nil, fmt.Errorf("failed to format generated code: %w", err)
	}

	return fmted, nil
}
